name: secp256r1
description: >
  A Flutter plugin that support secp256r1 by Keystore on Android and Secure Enclave on iOS.
version: 0.1.0-dev.7
repository: https://github.com/AstroxNetwork/flutter_secp256r1

environment:
  sdk: '>=2.13.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  agent_dart:
    git:
      url: https://github.com/AstroxNetwork/agent_dart
      ref: c053ad080c87fd5b036e0844d619bec023bd0abc
  plugin_platform_interface: ^2.0.2
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: com.astrox.secure_p256_plugin
        pluginClass: SecureP256Plugin
      ios:
        pluginClass: SecureP256Plugin
